FROM registry.fluves.net/drone/infrastructure/conda-bullseye
RUN apt-get update -q && \
    apt-get dist-upgrade -yq && \
    apt-get install -q -y --no-install-recommends \
        git-lfs \
        lcl-utils-2.0 \
        lcl-2.0 \
        make \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
