name: build_packages

on:
  workflow_call:
  workflow_dispatch:
  push:

env:
  DEBIAN_RSYNC_TARGET: /appdata/static/apt/amd64
  DRONE_BUILD_NUMBER: ${{ github.run_number }}
  RSYNC_USER: docs
  RSYNC_HOST: ijzer
jobs:
  build-linux:
    runs-on: [ubuntu-latest]
    container: ghcr.io/watem-sedem/ci/watem-sedem-conda
    env:
      PYTHONPATH: ../CNWS-processing-scripts/pycnws/src
    steps:
      - uses: actions/checkout@v4
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          fetch-tags: true
          lfs: true
      - uses: actions/checkout@v4
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          lfs: true
      - name: build linux
        run: |
          make

      - name: test watem-sedem runs without error
        run: |
          testfiles/test.sh

      - name: CNWS-processing repo for python tests
        shell: bash
        run: |
          source /etc/profile.d/conda.sh
          conda env create -f environment.yml
          conda activate watem_sedem
          pytest testfiles
      - uses: actions/upload-artifact@master
        with:
          name: linux-amd64-binary
          path: watem_sedem/watem_sedem

  build-debian:
    runs-on: [ubuntu-latest]
    container: ghcr.io/watem-sedem/ci/debian11-build
    env:
      DEBFULLNAME: "Fluves Drone CI"
      DEBEMAIL: donotreply@fluves.net
    steps:
      # don't fetch tags if building on a tag, because then a conflict is raised
      - uses: actions/checkout@v4
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          fetch-tags: true
          lfs: true
      - uses: actions/checkout@v4
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          lfs: true
      - name: build debian package
        run : |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          gbp dch --ignore-branch --new-version=$(git describe --tags) --snapshot-number=$DRONE_BUILD_NUMBER --snapshot
          debuild -b
          mkdir /package
          mv ../watem-sedem*amd64* /package
      - uses: actions/upload-artifact@master
        with:
          name: debian-output
          path: /package
          
  build-documentation:
    needs: [build-linux]
    runs-on: [ubuntu-latest]  
    container: ghcr.io/watem-sedem/ci/watem-sedem-conda
    steps:
      - uses: actions/checkout@v4
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          fetch-tags: true
          lfs: true
      - uses: actions/checkout@v4
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          lfs: true

      - name: build website
        shell: bash
        run: |
          pip install -r ./docs/requirements.txt
          sphinx-build ./docs ./docs/_build/

      - uses: actions/upload-artifact@master
        with:
          name: documentation-output
          path: ./docs
